version: '3'
services:
  frontend:
    build: frontend
    volumes:
      - /app/node_modules
      - files:/usr/share/nginx/html/files
  backend:
    build: backend
    volumes:
      - /app/node_modules
      - files:/app/files
  proxy:
    build: proxy
    restart: always
    ports:
      - '3050:80'
volumes:
  files: