version: '3'
services:
  frontend:
    build: frontend
  backend:
    build: backend
    volumes:
      - ./backend/files:/usr/src/app/files
  proxy:
    build: proxy
    restart: always
    volumes:
      - ./backend/files:/usr/share/nginx/html/files
    ports:
      - "61019:80"
volumes:
  files: